[general]
live_config_reload = true
working_directory = "None"
ipc_socket = true
import = ["~/.config/alacritty/keys.toml"]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 16, y = 0 }
dynamic_padding = true
decorations = "Buttonless"
startup_mode = "Maximized"                 # change require restart
opacity = 0.75
blur = true

[scrolling]
history = 10000
multiplier = 3  # scroll distance multiplier

[keyboard]
bindings = []

[bell]
animation = "EaseOutExpo"
duration = 200
color = '#aa0000'
# command = { program = "noti", args = [ "-t", "BELL" ] }

[selection]
save_to_clipboard = true


[cursor]
unfocused_hollow = true
blink_interval = 500
blink_timeout = 15
thickness = 0.50
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Beam", blinking = "Never" }

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Left", mods = "Shift|Control", action = "ExpandSelection" },
]

[hints]
alphabet = "asdfjkl;"

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "open"
hyperlinks = true
action = "Copy"
post_processing = true
persist = false
mouse.enabled = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[colors]
transparent_background_colors = true
# draw_bold_text_with_bright_colors = true # non default

# kurokula

[colors.bright]
black = '#515151'
blue = '#a1d9ff'
cyan = '#f9cfb9'
green = '#c1ffae'
magenta = '#a994ff'
red = '#ffc663'
white = '#ffffff'
yellow = '#fff700'

[colors.normal]
black = '#333333'
blue = '#6890d7'
cyan = '#837369'
green = '#85b1a9'
magenta = '#887aa3'
red = '#b66056'
white = '#ddd0c4'
yellow = '#dbbb43'

[colors.primary]
background = '#141515'
foreground = '#ddd0c4'

[colors.selection]
background = '#515151'
text = '#ffc663'

[colors.cursor]
cursor = "#ffc663"
text = "#141515"

[colors.search]
matches = { background = "#515151", foreground = "#ffc663" }
focused_match = { background = "#ffc663", foreground = "#000000" }

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#ffa2ed"

[colors.footer_bar]
background = "#515151"
foreground = "#ffc663"

[colors.hints]
start = { background = "#d23e08", foreground = "#ffffff" }
end = { background = "#2ab9ff", foreground = "#ffffff" }
