theme = "kurokula"

[keys.normal]
"A-/" = "toggle_comments"
"C-y" = ":clipboard-yank"
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"
"{" = "rotate_selection_contents_backward"
"}" = "rotate_selection_contents_forward"
"S-left" = "select_mode"
"S-right" = "select_mode"

[keys.select]
"C-c" = ":clipboard-yank"
"S-left" = "move_char_left"
"S-right" = "move_char_right"
"S-up" = "move_visual_line_up"
"S-down" = "move_visual_line_down"

[keys.normal.","]
"/" = "toggle_comments"
"p" = ":clipboard-paste-after"
"P" = ":clipboard-paste-before"
"," = "keep_primary_selection"

[editor]
bufferline = "multiple"
shell = ["zsh", "-c"]
line-number = "absolute"
cursorline = true
color-modes = true


[editor.statusline]
left = [
  "mode",
  "selections",
  "spacer",
  "spinner",
  "diagnostics"
]
center = [
  # "separator",
  "version-control",
  "file-name",
  "file-modification-indicator",
  "file-encoding",
]
right = [
  "diagnostics",
  "file-type",
  "file-encoding",
  "file-line-ending",
  "position",
  "position-percentage",
]
separator = "│"
mode.normal = "● nor"
mode.insert = "◉ ins"
mode.select = "◍ sel"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "underline"
select = "bar"

[editor.file-picker]
hidden = false

# [editor.whitespace]
# or control each character

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
# space = "·"
nbsp = "⍽"
tab = "→"
# newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.gutters]
layout = ["diagnostics", "line-numbers", "diff"]
# gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.gutters.line-numbers]
min-width = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = "..."  # set wrap-indicator to "" to hide it


