[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Insert", mods = "Shift", action = "PasteSelection" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "J", mods = "Command|Alt", action = "ScrollLineDown" },
  { key = "K", mods = "Command|Alt", action = "ScrollLineUp" },
  { key = "N", mods = "Command", action = "CreateNewWindow" },
  { key = "V", mods = "Alt|Shift|Control", action = "ToggleViMode" },
  { key = "ArrowRight", action = "SearchFocusNext", mode = "Search" },
  { key = "ArrowLeft", action = "SearchFocusPrevious", mode = "Search" },
  { key = "?", mods = "Shift|Control", action = "SearchForward" },
]

[window]
option_as_alt = "OnlyLeft"

[font]
size = 16
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Light" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "ExtraBold Italic" }
builtin_box_drawing = false

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]
