#!/usr/bin/env zsh

mv formulae-casks.csv "formulae-casks-`date +%Y-%m-%d`.csv"

formulae=($(brew leaves --installed-on-request))
casks=($(brew list --cask))
output="name,version,date,description,status,type"

function addrow() {
	name=$1
	type=$2
	info=`brew info $name`
	url=`rg ^http <<< $info`
	date=`rg Poured <<< $info | rg -o '(\d+\-){2}\d+' || rg /usr <<< $info | head --line 1 | sd ' \(.*\)[ \s]+' '' | xargs stat -f "%SB" | xargs -I {} date -j -f "%b %d %T %Y" {} "+%Y-%m-%d"`
	version=`rg "==> $name:" <<< $info | rg -o '((\d+\.*)+)' | head --line 1`
	append="\n$output$name,$version,$date,description,installed,$type"
	output=$append
}

for i in {1..$#formulae}; do
	addrow $formulae[i] formula
done

for i in {1..$#casks}; do
	addrow $casks[i] cask
done

echo $output > temp.csv
csvsort -c name temp.csv > formulae-casks.csv
rm temp.csv
