# kuruku

spacing            = 1
padding            = 0
hide_ascii         = false
separator          = "❯"
key_color          = "Green"
separator_color    = "Blue"
prefer_small_ascii = true

[palette]
type = "Dark"
glyph = "█ "
visible = true

[bar]
glyph           = "●"
symbol_open     = '⎪'
symbol_close    = '⎪'
hide_delimiters = true
visible         = true

[box]
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 2
y               = 1

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "HOST"
kernel          = "KERNEL"
battery         = "BAT"
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "DIST"
terminal        = "TERM"
shell           = "SHELL"
packages        = "PKGS"
uptime          = "UP"
memory          = "MDM"
machine         = "Machine"
local_ip        = "IP"
backlight       = "LIGHT"
resolution      = "RES"
cpu_load        = "Load"
cpu             = "CPU"
gpu             = "GPU"
disk_space      = "DU"
