# Specifies the network interface to use for the LocalIP readout
interface = "wlan0"

# Lengthen uptime output
long_uptime = false

# Lengthen shell output
long_shell = true

# Lengthen kernel output
long_kernel = false

# Toggle between displaying the current shell or your user's default one.
current_shell = true

# Toggle between displaying the number of physical or logical cores of your
# processor.
physical_cores = true

# Disks to show disk usage for. Defaults to `["/"]`.
# disks = ["/", "/home/user"]

# Show percentage next to disk usage
# disk_usage = true

# Themes need to be placed in "$XDG_CONFIG_DIR/macchina/themes" beforehand.
# e.g.:
#  if theme path is /home/foo/.config/macchina/themes/Sodium.toml
#  theme should be uncommented and set to "Sodium"
#
theme = "kuroku"

# Displays only the specified readouts.
# Accepted values (case-sensitive):
  show = [
    # "Host",
    # "Machine",
    "Distribution",
    "Kernel",
    "OperatingSystem",
    "DesktopEnvironment",
    "WindowManager",
    "Packages",
    "Shell",
    "Terminal",
    "LocalIP",
    "Uptime",
    "Processor",
    "ProcessorLoad",
    "Memory",
    "Battery",
    "DiskSpace",
    "Backlight",
    "Resolution"
]
