#!/usr/bin/env zsh

konfdir="alacritty"
confdir="$HOME/.config/$konfdir"
conf="$confdir/alacritty.yml"

function linkconf() {
	if [[ $OSTYPE == darwin* ]] then
		ln -s "$KUTEN/$konfdir/mac-alacritty.yml" $conf
	elif [[ $OSTYPE == linux* ]] then
		ln -s "$KUTEN/$konflinux" $conf
		ln -s "$KUTEN/$konfdir/linux-alacritty.yml" $conf
	fi
}

if [[ -d "$confdir" ]] then
	echo "$confdir exist"

	if [[ -f $conf || -h $conf ]] then
		mv $conf "$conf-backup-`date -u +%Y-%m-%dT%H:%M:%S%Z`"
		echo "backup $conf"
		linkconf
	else
		echo "$conf doesn't exist..."
		linkconf
	fi

else
	echo "$confdir doesn't exist... create dir"
	mkdir $confdir
	linkconf
fi
